# Generated by Django 3.0.4 on 2020-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('mark', models.IntegerField(blank=True, choices=[('2', 'Неудовлетворительно'), ('3', 'Удовлетворительно'), ('4', 'Хорошо'), ('5', 'Отлично')])),
            ],
        ),
    ]
