# Generated by Django 2.2 on 2020-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(2, 'Неудовлетворительно'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')]),
        ),
    ]
